#!/bin/sh
# postrm script for rabbitmq-server-parsec

if [ -f /etc/parsec/privsock.conf ]; then
    sed -i '#/usr/lib/rabbitmq/bin/rabbitmq-server#d' /etc/parsec/privsock.conf
fi

# DEBHELPER

exit 0

